import type { RootAPI, File } from "$lib/api";


export let sampleFiles: File[] = [
    {
        id: 1,
        name: "public",
        created_at: "",
        is_folder: true,
        path: "",
        size: 0,
        ftype: "project",
        hash: "",
        mime: "",
        external: false,
        is_public: false,
        owner_user_id: 0,
        owner_proj_id: 0,
    },
    {
        id: 2,
        name: "test.mp4",
        created_at: "2022/03/45",
        size: 23000000,
        ftype: "project",
        hash: "",
        mime: "",
        external: false,
        is_public: false,
        owner_user_id: 0,
        owner_proj_id: 0,
        path: "",
        is_folder: false,
    },
    {
        id: 3,
        name: "test.zip",
        created_at: "2022/03/45",
        size: 1000,
        ftype: "project",
        hash: "",
        mime: "",
        external: false,
        is_public: false,
        owner_user_id: 0,
        owner_proj_id: 0,
        path: "",
        is_folder: false,
    },
    {
        id: 4,
        name: "test.png",
        created_at: "2022/03/45",
        size: 1000,
        ftype: "project",
        hash: "",
        mime: "",
        external: false,
        is_public: false,
        owner_user_id: 0,
        owner_proj_id: 0,
        path: "",
        is_folder: false,
    },
    {
        id: 5,
        name: "xyz.mp3",
        created_at: "2022/03/45",
        size: 1000,
        ftype: "project",
        hash: "",
        mime: "",
        external: false,
        is_public: false,
        owner_user_id: 0,
        owner_proj_id: 0,
        path: "",
        is_folder: false,
    },
    {
        id: 6,
        name: "test.txt",
        created_at: "2022/03/45",
        size: 1000,
        ftype: "project",
        hash: "",
        mime: "",
        external: false,
        is_public: false,
        owner_user_id: 0,
        owner_proj_id: 0,
        path: "",
        is_folder: false,
    },
];