
-- TRACKER APP

create table __project__Events(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    etype TEXT NOT NULL DEFAULT 'normal',
    name TEXT NOT NULL DEFAULT '',
    info TEXT NOT NULL DEFAULT '',
    lat FLOAT NOT NULL DEFAULT 0,
    lng FLOAT NOT NULL DEFAULT 0,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);


-- SLEEP TRACKER APP


create table __project__SleepEvents(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);


create table __project__Sleeps(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    attempt_sucessful BOOLEAN NOT NULL DEFAULT FALSE,
    depth_of_sleep INTEGER NOT NULL DEFAULT 0,
    after_brain_fog INTEGER NOT NULL DEFAULT 0
);
